version:  '3.6'

services:

  postgres:
    image: postgres:11-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_NAME
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - ./postgresql/dumps:/code/dumps
      - ./postgresql/data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ['./code/docker-entrypoint.sh']
    expose:
      - 8080
    env_file:
      - .env
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - postgres
    volumes:
      - ./public:/code/public
      - ./uploads:/code/uploads
