# Generated by Django 3.2.5 on 2022-08-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_capacity', models.IntegerField(default=200, verbose_name='Base fuel tank capacity (liters)')),
            ],
        ),
    ]
